### ISSUE TITLE
corsPolicy not adding origins

### ISSUE THREAD

**Issue by randallto** [MirzaMerdovic/WebApiStartTemplate#3]
Great template! Thanks. I had to make this one change to use cors origins in CorConfig.cs
This was not adding the origins list:
corsPolicy.Origins.ToList().AddRange(origins.Split(';'));

Ended up replacing it with:
            foreach(var item in origins.Split(';'))
            {
                corsPolicy.Origins.Add(item);
            }

**Comment by MirzaMerdovic** [comment]
Hi,

Thanks and thanks for the feedback. I see how this might not work because of the ToList() call.

I will look into it.
